---
language: "python"
python: "2.7"

env:
  - SITE_AND_INVENTORY="tests/test.yml -i tests/inventory"

before_install:
  - "sudo apt-get update -qq"

install:
  - "pip install ansible==1.6.2"
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
  - "ansible-playbook $SITE_AND_INVENTORY --syntax-check"
  - "ansible-playbook $SITE_AND_INVENTORY --connection=local -vvvv"
  - >
    ansible-playbook $SITE_AND_INVENTORY --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - >
    sudo monit -t
    && (echo 'Valid config test: pass' && exit 0)
    || (echo 'Valid config test: fail' && exit 1)
  - >
    sudo monit status
    | grep -q 'ssh'
    && (echo 'Status test: pass' && exit 0)
    || (echo 'Status test: fail' && exit 1)
  - ansible-playbook $SITE_AND_INVENTORY --connection=local --extra-vars '{"monit_process_list":["process": "ssh","pid_path": "/var/run/sshd.pid",delete: true]}'
  - >
    sudo monit status
    | grep -q 'ssh'
    && (echo 'No status test: pass' && exit 1)
    || (echo 'No status test: fail' && exit 0)